#!/bin/bash

ENVIRONMENT=$(echo $DOCKER_TAG | cut -d "-" -f1)

SERVER_VERSION=$(docker version -f "{{.Server.Version}}")

echo -e "$SERVER_VERSION"

if [ $DOCKER_TAG == "latest" ]
then
  echo -e "building image using PORT: $PORT"
  docker build --build-arg PORT=$PORT -f $DOCKERFILE_PATH -t $IMAGE_NAME .
else
  echo -e "building image using PORT: $PORT_STAGE"
  docker build --build-arg PORT=$PORT_STAGE -f $DOCKERFILE_PATH -t $IMAGE_NAME .
fi